on:
  push:
    branches:
        - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: aws-actions/setup-sam@v2
              with:
                use-installer: true
            - uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            - uses: actions/setup-go@v2
              with:
                go-version: '1.21'
            - run: |
                folders=(
                    "yt-dl-ms-lambda"
                )
                for folder in "${folders[@]}"; do
                    cd $folder
                    go mod tidy -go=1.21
                    cd ../
                done
            - run: sam build
            - run: |
                mkdir bin
                cd bin
                wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
                mkdir ffmpeg
                tar -xf ffmpeg-git-amd64-static.tar.xz -C ffmpeg --strip-components=1
                cd ../
                cp bin/ffmpeg/ffmpeg .aws-sam/build/ConvertTrackFunction/

            - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name yt-dl-ms --region us-east-2 --parameter-overrides JwtSec=${{ secrets.JWT_SECRET }}